// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using PluginConfiguration within kubernetes types, where deepcopy-gen is used.
func (in *PluginConfiguration) DeepCopyInto(out *PluginConfiguration) {
	p := proto.Clone(in).(*PluginConfiguration)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfiguration. Required by controller-gen.
func (in *PluginConfiguration) DeepCopy() *PluginConfiguration {
	if in == nil {
		return nil
	}
	out := new(PluginConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfiguration. Required by controller-gen.
func (in *PluginConfiguration) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NodeConfiguration within kubernetes types, where deepcopy-gen is used.
func (in *NodeConfiguration) DeepCopyInto(out *NodeConfiguration) {
	p := proto.Clone(in).(*NodeConfiguration)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfiguration. Required by controller-gen.
func (in *NodeConfiguration) DeepCopy() *NodeConfiguration {
	if in == nil {
		return nil
	}
	out := new(NodeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfiguration. Required by controller-gen.
func (in *NodeConfiguration) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using PluginInfo within kubernetes types, where deepcopy-gen is used.
func (in *PluginInfo) DeepCopyInto(out *PluginInfo) {
	p := proto.Clone(in).(*PluginInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginInfo. Required by controller-gen.
func (in *PluginInfo) DeepCopy() *PluginInfo {
	if in == nil {
		return nil
	}
	out := new(PluginInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new PluginInfo. Required by controller-gen.
func (in *PluginInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AuthenticationRequest within kubernetes types, where deepcopy-gen is used.
func (in *AuthenticationRequest) DeepCopyInto(out *AuthenticationRequest) {
	p := proto.Clone(in).(*AuthenticationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationRequest. Required by controller-gen.
func (in *AuthenticationRequest) DeepCopy() *AuthenticationRequest {
	if in == nil {
		return nil
	}
	out := new(AuthenticationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationRequest. Required by controller-gen.
func (in *AuthenticationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AuthenticationResponse within kubernetes types, where deepcopy-gen is used.
func (in *AuthenticationResponse) DeepCopyInto(out *AuthenticationResponse) {
	p := proto.Clone(in).(*AuthenticationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationResponse. Required by controller-gen.
func (in *AuthenticationResponse) DeepCopy() *AuthenticationResponse {
	if in == nil {
		return nil
	}
	out := new(AuthenticationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationResponse. Required by controller-gen.
func (in *AuthenticationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Event within kubernetes types, where deepcopy-gen is used.
func (in *Event) DeepCopyInto(out *Event) {
	p := proto.Clone(in).(*Event)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Event. Required by controller-gen.
func (in *Event) DeepCopy() *Event {
	if in == nil {
		return nil
	}
	out := new(Event)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Event. Required by controller-gen.
func (in *Event) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AllocateIPRequest within kubernetes types, where deepcopy-gen is used.
func (in *AllocateIPRequest) DeepCopyInto(out *AllocateIPRequest) {
	p := proto.Clone(in).(*AllocateIPRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocateIPRequest. Required by controller-gen.
func (in *AllocateIPRequest) DeepCopy() *AllocateIPRequest {
	if in == nil {
		return nil
	}
	out := new(AllocateIPRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AllocateIPRequest. Required by controller-gen.
func (in *AllocateIPRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AllocatedIP within kubernetes types, where deepcopy-gen is used.
func (in *AllocatedIP) DeepCopyInto(out *AllocatedIP) {
	p := proto.Clone(in).(*AllocatedIP)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocatedIP. Required by controller-gen.
func (in *AllocatedIP) DeepCopy() *AllocatedIP {
	if in == nil {
		return nil
	}
	out := new(AllocatedIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AllocatedIP. Required by controller-gen.
func (in *AllocatedIP) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ReleaseIPRequest within kubernetes types, where deepcopy-gen is used.
func (in *ReleaseIPRequest) DeepCopyInto(out *ReleaseIPRequest) {
	p := proto.Clone(in).(*ReleaseIPRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseIPRequest. Required by controller-gen.
func (in *ReleaseIPRequest) DeepCopy() *ReleaseIPRequest {
	if in == nil {
		return nil
	}
	out := new(ReleaseIPRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseIPRequest. Required by controller-gen.
func (in *ReleaseIPRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
