//
//Copyright 2023 Avi Zimmerman <avi.zimmerman@gmail.com>
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-connect-es v1.1.2
// @generated from file v1/mesh.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetNodeRequest, MeshGraph } from "./mesh_pb.js";
import { MeshNode, NodeList } from "./node_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * Mesh is a service that can optionally be exposed by a node. It provides methods for 
 * interfacing with the webmesh from the outside.
 *
 * @generated from service v1.Mesh
 */
export declare const Mesh: {
  readonly typeName: "v1.Mesh",
  readonly methods: {
    /**
     * GetNode gets a node by ID.
     *
     * @generated from rpc v1.Mesh.GetNode
     */
    readonly getNode: {
      readonly name: "GetNode",
      readonly I: typeof GetNodeRequest,
      readonly O: typeof MeshNode,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ListNodes lists all nodes.
     *
     * @generated from rpc v1.Mesh.ListNodes
     */
    readonly listNodes: {
      readonly name: "ListNodes",
      readonly I: typeof Empty,
      readonly O: typeof NodeList,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetMeshGraph fetches the mesh graph. It returns a list of nodes,
     * edges, and a rendering in the dot format.
     *
     * @generated from rpc v1.Mesh.GetMeshGraph
     */
    readonly getMeshGraph: {
      readonly name: "GetMeshGraph",
      readonly I: typeof Empty,
      readonly O: typeof MeshGraph,
      readonly kind: MethodKind.Unary,
    },
  }
};

