//
//Copyright 2023 Avi Zimmerman <avi.zimmerman@gmail.com>
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-es v1.4.0
// @generated from file v1/mesh.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * GetNodeRequest is a request to get a node.
 *
 * @generated from message v1.GetNodeRequest
 */
export const GetNodeRequest = proto3.makeMessageType(
  "v1.GetNodeRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * MeshEdge is an edge between two nodes.
 *
 * @generated from message v1.MeshEdge
 */
export const MeshEdge = proto3.makeMessageType(
  "v1.MeshEdge",
  () => [
    { no: 1, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "target", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "weight", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "attributes", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ],
);

/**
 * MeshEdges is a list of edges.
 *
 * @generated from message v1.MeshEdges
 */
export const MeshEdges = proto3.makeMessageType(
  "v1.MeshEdges",
  () => [
    { no: 1, name: "items", kind: "message", T: MeshEdge, repeated: true },
  ],
);

/**
 * MeshGraph is a graph of nodes.
 *
 * @generated from message v1.MeshGraph
 */
export const MeshGraph = proto3.makeMessageType(
  "v1.MeshGraph",
  () => [
    { no: 1, name: "nodes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "edges", kind: "message", T: MeshEdge, repeated: true },
    { no: 3, name: "dot", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

