// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using FeaturePort within kubernetes types, where deepcopy-gen is used.
func (in *FeaturePort) DeepCopyInto(out *FeaturePort) {
	p := proto.Clone(in).(*FeaturePort)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturePort. Required by controller-gen.
func (in *FeaturePort) DeepCopy() *FeaturePort {
	if in == nil {
		return nil
	}
	out := new(FeaturePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FeaturePort. Required by controller-gen.
func (in *FeaturePort) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MeshNode within kubernetes types, where deepcopy-gen is used.
func (in *MeshNode) DeepCopyInto(out *MeshNode) {
	p := proto.Clone(in).(*MeshNode)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshNode. Required by controller-gen.
func (in *MeshNode) DeepCopy() *MeshNode {
	if in == nil {
		return nil
	}
	out := new(MeshNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MeshNode. Required by controller-gen.
func (in *MeshNode) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NodeList within kubernetes types, where deepcopy-gen is used.
func (in *NodeList) DeepCopyInto(out *NodeList) {
	p := proto.Clone(in).(*NodeList)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeList. Required by controller-gen.
func (in *NodeList) DeepCopy() *NodeList {
	if in == nil {
		return nil
	}
	out := new(NodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NodeList. Required by controller-gen.
func (in *NodeList) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetStatusRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetStatusRequest) DeepCopyInto(out *GetStatusRequest) {
	p := proto.Clone(in).(*GetStatusRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetStatusRequest. Required by controller-gen.
func (in *GetStatusRequest) DeepCopy() *GetStatusRequest {
	if in == nil {
		return nil
	}
	out := new(GetStatusRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetStatusRequest. Required by controller-gen.
func (in *GetStatusRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Status within kubernetes types, where deepcopy-gen is used.
func (in *Status) DeepCopyInto(out *Status) {
	p := proto.Clone(in).(*Status)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status. Required by controller-gen.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Status. Required by controller-gen.
func (in *Status) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DataChannelNegotiation within kubernetes types, where deepcopy-gen is used.
func (in *DataChannelNegotiation) DeepCopyInto(out *DataChannelNegotiation) {
	p := proto.Clone(in).(*DataChannelNegotiation)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataChannelNegotiation. Required by controller-gen.
func (in *DataChannelNegotiation) DeepCopy() *DataChannelNegotiation {
	if in == nil {
		return nil
	}
	out := new(DataChannelNegotiation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DataChannelNegotiation. Required by controller-gen.
func (in *DataChannelNegotiation) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using InterfaceMetrics within kubernetes types, where deepcopy-gen is used.
func (in *InterfaceMetrics) DeepCopyInto(out *InterfaceMetrics) {
	p := proto.Clone(in).(*InterfaceMetrics)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceMetrics. Required by controller-gen.
func (in *InterfaceMetrics) DeepCopy() *InterfaceMetrics {
	if in == nil {
		return nil
	}
	out := new(InterfaceMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceMetrics. Required by controller-gen.
func (in *InterfaceMetrics) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using PeerMetrics within kubernetes types, where deepcopy-gen is used.
func (in *PeerMetrics) DeepCopyInto(out *PeerMetrics) {
	p := proto.Clone(in).(*PeerMetrics)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerMetrics. Required by controller-gen.
func (in *PeerMetrics) DeepCopy() *PeerMetrics {
	if in == nil {
		return nil
	}
	out := new(PeerMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new PeerMetrics. Required by controller-gen.
func (in *PeerMetrics) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using WebRTCSignal within kubernetes types, where deepcopy-gen is used.
func (in *WebRTCSignal) DeepCopyInto(out *WebRTCSignal) {
	p := proto.Clone(in).(*WebRTCSignal)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebRTCSignal. Required by controller-gen.
func (in *WebRTCSignal) DeepCopy() *WebRTCSignal {
	if in == nil {
		return nil
	}
	out := new(WebRTCSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new WebRTCSignal. Required by controller-gen.
func (in *WebRTCSignal) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
