// Code generated by protoc-gen-deepcopy. DO NOT EDIT.

package v1

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using Rule within kubernetes types, where deepcopy-gen is used.
func (in *Rule) DeepCopyInto(out *Rule) {
	p := proto.Clone(in).(*Rule)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule. Required by controller-gen.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Rule. Required by controller-gen.
func (in *Rule) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Role within kubernetes types, where deepcopy-gen is used.
func (in *Role) DeepCopyInto(out *Role) {
	p := proto.Clone(in).(*Role)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Role. Required by controller-gen.
func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := new(Role)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Role. Required by controller-gen.
func (in *Role) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Roles within kubernetes types, where deepcopy-gen is used.
func (in *Roles) DeepCopyInto(out *Roles) {
	p := proto.Clone(in).(*Roles)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Roles. Required by controller-gen.
func (in *Roles) DeepCopy() *Roles {
	if in == nil {
		return nil
	}
	out := new(Roles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Roles. Required by controller-gen.
func (in *Roles) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RoleBinding within kubernetes types, where deepcopy-gen is used.
func (in *RoleBinding) DeepCopyInto(out *RoleBinding) {
	p := proto.Clone(in).(*RoleBinding)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleBinding. Required by controller-gen.
func (in *RoleBinding) DeepCopy() *RoleBinding {
	if in == nil {
		return nil
	}
	out := new(RoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RoleBinding. Required by controller-gen.
func (in *RoleBinding) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RoleBindings within kubernetes types, where deepcopy-gen is used.
func (in *RoleBindings) DeepCopyInto(out *RoleBindings) {
	p := proto.Clone(in).(*RoleBindings)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleBindings. Required by controller-gen.
func (in *RoleBindings) DeepCopy() *RoleBindings {
	if in == nil {
		return nil
	}
	out := new(RoleBindings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RoleBindings. Required by controller-gen.
func (in *RoleBindings) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Subject within kubernetes types, where deepcopy-gen is used.
func (in *Subject) DeepCopyInto(out *Subject) {
	p := proto.Clone(in).(*Subject)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subject. Required by controller-gen.
func (in *Subject) DeepCopy() *Subject {
	if in == nil {
		return nil
	}
	out := new(Subject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Subject. Required by controller-gen.
func (in *Subject) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Group within kubernetes types, where deepcopy-gen is used.
func (in *Group) DeepCopyInto(out *Group) {
	p := proto.Clone(in).(*Group)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group. Required by controller-gen.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Group. Required by controller-gen.
func (in *Group) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Groups within kubernetes types, where deepcopy-gen is used.
func (in *Groups) DeepCopyInto(out *Groups) {
	p := proto.Clone(in).(*Groups)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Groups. Required by controller-gen.
func (in *Groups) DeepCopy() *Groups {
	if in == nil {
		return nil
	}
	out := new(Groups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Groups. Required by controller-gen.
func (in *Groups) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RBACAction within kubernetes types, where deepcopy-gen is used.
func (in *RBACAction) DeepCopyInto(out *RBACAction) {
	p := proto.Clone(in).(*RBACAction)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACAction. Required by controller-gen.
func (in *RBACAction) DeepCopy() *RBACAction {
	if in == nil {
		return nil
	}
	out := new(RBACAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RBACAction. Required by controller-gen.
func (in *RBACAction) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
